USE [C:\USERS\KIREINO\DOCUMENTS\VISUAL STUDIO 2013\PROJECTS\VISERVER\VISERVER\DB_VISERVER.MDF]
GO

sp_configure 'show advanced options',1
GO
RECONFIGURE WITH OVERRIDE
GO
sp_configure 'contained database authentication', 1
GO
RECONFIGURE WITH OVERRIDE
GO

ALTER DATABASE CURRENT SET CONTAINMENT = PARTIAL;